apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadbrsa1456-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadbrsa1456-tenant-component
    app.kubernetes.io/part-of: loadbrsa1456-tenant-app
  name: loadbrsa1456-tenant-component
  namespace: loadbrsa1456-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadbrsa1456-tenant-component
    weight: null
status: {}
